[package]
name = "rust_tcp_sever"
version = "0.1.1"
authors = ["AmakeSasha amakesasha@gmail.com"]
license = "MIT license"
description = "A simple and lightweight crate for launching and using a server"

repository = "https://github.com/Amakesasha/Rust-TcpServer"
readme = "README.md"

[dependencies]
