[package]
name = "rust_tcp_sever"
version = "0.2.1"
authors = ["AmakeSasha <amakesasha@gmail.com>"]
edition = "2021"
description = "A simple and lightweight crate for launching and using a server."
readme = "README.md"
repository = "https://github.com/Amakesasha/Rust-TcpSever"
license = "MIT"
keywords = ["tcp_server", "rust_server", "rust_tcp_server", "web", "tcp", "server"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
lazy_static = "1.5.0"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false