[package]
name = "rust_tcp_sever"
version = "0.2.0"

authors = ["AmakeSasha amakesasha@gmail.com"]
description = "A simple and lightweight crate for launching and using a server"

license = "MIT"
repository = "https://github.com/Amakesasha/Rust-TcpSever"
readme = "README.md"

keywords = ["tcp_server", "rust_server", "rust_tcp_server", "web", "tcp"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
lazy_static = "1.5.0"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false